name: XSEED Organization CI

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: [ $default-branch ]
  
  workflow_dispatch:
    inputs:
      infraEnv:
        description: 'Env (staging/prep/qa)'     
        required: true
        default: 'staging'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello from Octo Organization